version: '3.2'

services:

  hello_container:
    environment:
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_HOST=postgres
      - DB_PORT=5432
    build: .
    volumes:
      - .:/hello_container
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b "0.0.0.0"'

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - /var/lib/postgresql/data
